iata_ger = {
    "Afghanistan": "KBL",
    "Ägypten": "CAI",
    "Albanien": "TIA",
    "Algerien": "ALG",
    "Andorra": "ALV",  # Placeholder code for Andorra
    "Angola": "LAD",
    "Antigua und Barbuda": "ANU",
    "Argentinien": "EZE",
    "Armenien": "EVN",
    "Australien": "SYD",
    "Österreich": "VIE",
    "Aserbaidschan": "GYD",
    "Bahamas": "NAS",
    "Bahrain": "BAH",
    "Bangladesch": "DAC",
    "Barbados": "BGI",
    "Weißrussland": "MSQ",
    "Belgien": "BRU",
    "Belize": "BZE",
    "Benin": "COO",
    "Bhutan": "PBH",
    "Bolivien": "VVI",
    "Bosnien und Herzegowina": "SJJ",
    "Botswana": "GBE",
    "Brasilien": "GRU",
    "Brunei": "BWN",
    "Bulgarien": "SOF",
    "Burkina Faso": "OUA",
    "Burundi": "BJM",
    "Cabo Verde": "SID",
    "Kambodscha": "PNH",
    "Kamerun": "DLA",
    "Kanada": "YYZ",
    "Zentralafrikanische Republik": "BGF",
    "Tschad": "NDJ",
    "Chile": "SCL",
    "China": "PEK",
    "Kolumbien": "BOG",
    "Komoren": "HAH",
    "Costa Rica": "SJO",
    "Kroatien": "ZAG",
    "Kuba": "HAV",
    "Zypern": "LCA",
    "Tschechische Republik": "PRG",
    "Demokratische Republik Kongo": "FIH",
    "Dänemark": "CPH",
    "Dschibuti": "JIB",
    "Dominica": "DOM",
    "Dominikanische Republik": "SDQ",
    "Ecuador": "UIO",
    "El Salvador": "SAL",
    "Äquatorialguinea": "SSG",
    "Eritrea": "ASM",
    "Estland": "TLL",
    "Eswatini": "SZK",
    "Äthiopien": "ADD",
    "Fidschi": "NAN",
    "Finnland": "HEL",
    "Frankreich": "CDG",
    "Gabun": "LBV",
    "Gambia": "BJL",
    "Georgien": "TBS",
    "Deutschland": "FRA",
    "Ghana": "ACC",
    "Griechenland": "ATH",
    "Grenada": "GND",
    "Guatemala": "GUA",
    "Guinea": "CKY",
    "Guinea-Bissau": "OXB",
    "Guyana": "GEO",
    "Haiti": "PAP",
    "Honduras": "TGU",
    "Ungarn": "BUD",
    "Island": "KEF",
    "Indien": "DEL",
    "Indonesien": "CGK",
    "Iran": "IKA",
    "Irak": "BGW",
    "Irland": "DUB",
    "Israel": "TLV",
    "Italien": "FCO",
    "Elfenbeinküste": "ABJ",
    "Jamaika": "KIN",
    "Japan": "HND",
    "Jordanien": "AMM",
    "Kasachstan": "ALA",
    "Kenia": "NBO",
    "Kiribati": "TRW",
    "Kuwait": "KWI",
    "Kirgisistan": "FRU",
    "Laos": "VTE",
    "Lettland": "RIX",
    "Libanon": "BEY",
    "Lesotho": "MSU",
    "Liberia": "ROB",
    "Libyen": "TIP",
    "Liechtenstein": "ACH",  # Placeholder code for Liechtenstein
    "Litauen": "VNO",
    "Luxemburg": "LUX",
    "Madagaskar": "TNR",
    "Malawi": "LLW",
    "Malaysia": "KUL",
    "Malediven": "MLE",
    "Mali": "BKO",
    "Malta": "MLA",
    "Marshallinseln": "MAJ",
    "Mauretanien": "NKC",
    "Mauritius": "MRU",
    "Mexiko": "MEX",
    "Mikronesien": "PNI",
    "Moldawien": "KIV",
    "Monaco": "MCM",
    "Mongolei": "ULN",
    "Montenegro": "TGD",
    "Marokko": "CMN",
    "Mosambik": "MPM",
    "Myanmar": "RGN",
    "Namibia": "WDH",
    "Nauru": "INU",
    "Nepal": "KTM",
    "Niederlande": "AMS",
    "Neuseeland": "AKL",
    "Nicaragua": "MGA",
    "Niger": "NIM",
    "Nigeria": "LOS",
    "Nordkorea": "FNJ",
    "Nordmazedonien": "SKP",
    "Norwegen": "OSL",
    "Oman": "MCT",
    "Pakistan": "ISB",
    "Palau": "ROR",
    "Panama": "PTY",
    "Papua-Neuguinea": "POM",
    "Paraguay": "ASU",
    "Peru": "LIM",
    "Philippinen": "MNL",
    "Polen": "WAW",
    "Portugal": "LIS",
    "Katar": "DOH",
    "Republik Kongo": "BZV",
    "Rumänien": "OTP",
    "Russland": "SVO",
    "Ruanda": "KGL",
    "St. Kitts und Nevis": "SKB",
    "St. Lucia": "UVF",
    "St. Vincent und die Grenadinen": "SVD",
    "Samoa": "APW",
    "San Marino": "RMI",
    "São Tomé und Príncipe": "TMS",
    "Saudi-Arabien": "JED",
    "Senegal": "DKR",
    "Serbien": "BEG",
    "Seychellen": "SEZ",
    "Sierra Leone": "FNA",
    "Singapur": "SIN",
    "Slowakei": "BTS",
    "Slowenien": "LJU",
    "Salomonen": "HIR",
    "Somalia": "MGQ",
    "Südafrika": "JNB",
    "Südkorea": "ICN",
    "Südsudan": "JUB",
    "Spanien": "MAD",
    "Sri Lanka": "CMB",
    "Sudan": "KRT",
    "Suriname": "PBM",
    "Schweden": "ARN",
    "Schweiz": "ZRH",
    "Syrien": "DAM",
    "Taiwan": "TPE",
    "Tadschikistan": "DYU",
    "Tansania": "JRO",
    "Thailand": "BKK",
    "Timor-Leste": "DIL",
    "Togo": "LFW",
    "Tonga": "TBU",
    "Trinidad und Tobago": "POS",
    "Tunesien": "TUN",
    "Türkei": "IST",
    "Turkmenistan": "ASB",
    "Tuvalu": "FUN",
    "Uganda": "EBB",
    "Ukraine": "KBP",
    "Vereinigte Arabische Emirate": "DXB",
    "Vereinigtes Königreich": "LHR",
    "Vereinigte Staaten": "ATL",
    "Uruguay": "MVD",
    "Usbekistan": "TAS",
    "Vanuatu": "VLI",
    "Vatikanstadt": "CIA",
    "Venezuela": "CCS",
    "Vietnam": "SGN",
    "Jemen": "SAH",
    "Sambia": "LUN",
    "Simbabwe": "HRE",
}

iata_eng = {
    "Afghanistan": "KBL",
    "Ägypten": "CAI",
    "Albania": "TIA",
    "Algeria": "ALG",
    "Andorra": "ALV",  # Placeholder code for Andorra
    "Angola": "LAD",
    "Antigua and Barbuda": "ANU",
    "Argentinien": "EZE",
    "Armenia": "EVN",
    "Australia": "SYD",
    "Austria": "VIE",
    "Azerbaijan": "GYD",
    "Bahamas": "NAS",
    "Bahrain": "BAH",
    "Bangladesh": "DAC",
    "Barbados": "BGI",
    "Belarus": "MSQ",
    "Belgium": "BRU",
    "Belize": "BZE",
    "Benin": "COO",
    "Bhutan": "PBH",
    "Bolivia": "VVI",
    "Bosnia and Herzegovina": "SJJ",
    "Botswana": "GBE",
    "Brazil": "GRU",
    "Brunei": "BWN",
    "Bulgaria": "SOF",
    "Burkina Faso": "OUA",
    "Burundi": "BJM",
    "Cabo Verde": "SID",
    "Cambodia": "PNH",
    "Cameroon": "DLA",
    "Canada": "YYZ",
    "Central African Republic": "BGF",
    "Chad": "NDJ",
    "Chile": "SCL",
    "China": "PEK",
    "Colombia": "BOG",
    "Comoros": "HAH",
    "Costa Rica": "SJO",
    "Croatia": "ZAG",
    "Cuba": "HAV",
    "Cyprus": "LCA",
    "Czech Republic": "PRG",
    "Democratic Republic of the Congo": "FIH",
    "Denmark": "CPH",
    "Djibouti": "JIB",
    "Dominica": "DOM",
    "Dominican Republic": "SDQ",
    "Ecuador": "UIO",
    "Egypt": "CAI",
    "El Salvador": "SAL",
    "Equatorial Guinea": "SSG",
    "Eritrea": "ASM",
    "Estonia": "TLL",
    "Eswatini": "SZK",
    "Ethiopia": "ADD",
    "Fiji": "NAN",
    "Finland": "HEL",
    "France": "CDG",
    "Gabon": "LBV",
    "Gambia": "BJL",
    "Georgia": "TBS",
    "Germany": "FRA",
    "Ghana": "ACC",
    "Greece": "ATH",
    "Grenada": "GND",
    "Guatemala": "GUA",
    "Guinea": "CKY",
    "Guinea-Bissau": "OXB",
    "Guyana": "GEO",
    "Haiti": "PAP",
    "Honduras": "TGU",
    "Hungary": "BUD",
    "Iceland": "KEF",
    "India": "DEL",
    "Indonesia": "CGK",
    "Iran": "IKA",
    "Iraq": "BGW",
    "Ireland": "DUB",
    "Israel": "TLV",
    "Italy": "FCO",
    "Ivory Coast": "ABJ",
    "Jamaica": "KIN",
    "Japan": "HND",
    "Jordan": "AMM",
    "Kazakhstan": "ALA",
    "Kenya": "NBO",
    "Kiribati": "TRW",
    "Kuwait": "KWI",
    "Kyrgyzstan": "FRU",
    "Laos": "VTE",
    "Latvia": "RIX",
    "Lebanon": "BEY",
    "Lesotho": "MSU",
    "Liberia": "ROB",
    "Libya": "TIP",
    "Liechtenstein": "ACH",  # Placeholder code for Liechtenstein
    "Lithuania": "VNO",
    "Luxembourg": "LUX",
    "Madagascar": "TNR",
    "Malawi": "LLW",
    "Malaysia": "KUL",
    "Maldives": "MLE",
    "Mali": "BKO",
    "Malta": "MLA",
    "Marshall Islands": "MAJ",
    "Mauritania": "NKC",
    "Mauritius": "MRU",
    "Mexico": "MEX",
    "Micronesia": "PNI",
    "Moldova": "KIV",
    "Monaco": "MCM",
    "Mongolia": "ULN",
    "Montenegro": "TGD",
    "Morocco": "CMN",
    "Mozambique": "MPM",
    "Myanmar": "RGN",
    "Namibia": "WDH",
    "Nauru": "INU",
    "Nepal": "KTM",
    "Netherlands": "AMS",
    "New Zealand": "AKL",
    "Nicaragua": "MGA",
    "Niger": "NIM",
    "Nigeria": "LOS",
    "North Korea": "FNJ",
    "North Macedonia": "SKP",
    "Norway": "OSL",
    "Oman": "MCT",
    "Pakistan": "ISB",
    "Palau": "ROR",
    "Panama": "PTY",
    "Papua New Guinea": "POM",
    "Paraguay": "ASU",
    "Peru": "LIM",
    "Philippines": "MNL",
    "Poland": "WAW",
    "Portugal": "LIS",
    "Qatar": "DOH",
    "Republic of the Congo": "BZV",
    "Romania": "OTP",
    "Russia": "SVO",
    "Rwanda": "KGL",
    "Saint Kitts and Nevis": "SKB",
    "Saint Lucia": "UVF",
    "Saint Vincent and the Grenadines": "SVD",
    "Samoa": "APW",
    "San Marino": "RMI",
    "São Tomé and Príncipe": "TMS",
    "Saudi Arabia": "JED",
    "Senegal": "DKR",
    "Serbia": "BEG",
    "Seychelles": "SEZ",
    "Sierra Leone": "FNA",
    "Singapore": "SIN",
    "Slovakia": "BTS",
    "Slovenia": "LJU",
    "Solomon Islands": "HIR",
    "Somalia": "MGQ",
    "South Africa": "JNB",
    "South Korea": "ICN",
    "South Sudan": "JUB",
    "Spain": "MAD",
    "Sri Lanka": "CMB",
    "Sudan": "KRT",
    "Suriname": "PBM",
    "Sweden": "ARN",
    "Switzerland": "ZRH",
    "Syria": "DAM",
    "Taiwan": "TPE",
    "Tajikistan": "DYU",
    "Tanzania": "JRO",
    "Thailand": "BKK",
    "Timor-Leste": "DIL",
    "Togo": "LFW",
    "Tonga": "TBU",
    "Trinidad and Tobago": "POS",
    "Tunisia": "TUN",
    "Turkey": "IST",
    "Turkmenistan": "ASB",
    "Tuvalu": "FUN",
    "Uganda": "EBB",
    "Ukraine": "KBP",
    "United Arab Emirates": "DXB",
    "United Kingdom": "LHR",
    "United States": "ATL",
    "USA": "ATL",
    "Uruguay": "MVD",
    "Uzbekistan": "TAS",
    "Vanuatu": "VLI",
    "Vatican City": "CIA",
    "Venezuela": "CCS",
    "Vietnam": "SGN",
    "Yemen": "SAH",
    "Zambia": "LUN",
    "Zimbabwe": "HRE",
    # Add more countries as needed
}
airports = iata_ger | iata_eng


def get_iata(landname: str):
    try:
        land = airports[landname]
        return land
    except:
        return "LAX"